---
name: 🚀 Feature Request
about: "I have a suggestion (and might want to implement myself \U0001F642)!"
labels: 
  - enhancement
assignees:
  - timo-reymann
body:
  - type: markdown
    attributes:
      description: Please leave a helpful description of the feature request here.
  - type: textarea
    id: references
    attributes:
      label: References
      description: |
        Are there any other GitHub issues (open or closed) or pull requests
        that should be linked here? Vendor documentation?
      placeholder: "You can reference issues with #"
---
